{% set name = "gcld3" %}
{% set version = "3.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcld3-{{ version }}.tar.gz
  sha256: 47c8c779bfe7372a38564b0cd357556dc362aec81cb55b0c889059e8b952e959

build:
  script:
    - {{ PYTHON }} -m pip install --use-pep517 . -vv
  number: 5
  skip: True  # [win or osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - libprotobuf
  host:
    - python
    - libprotobuf
    - pybind11 >=2.5.0
    - wheel >=0.34.2
    - pip
  run:
    - python

test:
  imports:
    - gcld3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/cld3
  summary: CLD3 is a neural network model for language identification.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgrbyte
